<div>
    <p class="text-retirada"><?= __('🏠 RECEIVE AT HOME or 🛒 RETURN FREE IN STORE') ?></p>
</div>

<!-- <div>
    <table>
        <thead>
            <tr>
                <th><?= __('Size') ?></th>
                <th><?= __('Dimensions') ?></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><?= __('S') ?></td>
                <td>x </td>
            </tr>
            <tr>
                <td><?= __('M') ?></td>
                <td>x </td>
            </tr>
            <tr>
                <td><?= __('L') ?></td>
                <td>X </td>
            </tr>
            <tr>
                <td><?= __('XL') ?></td>
                <td>X </td>
            </tr>
        </tbody>
    </table>
</div> -->

